### ISSUE TITLE
Quits after reading an event

### ISSUE THREAD

**Issue by Lythenas** [piutranq/sxhkd-statusd#1]
After reading one event the program exits with exit code 141.

```
$ ./prefix/sxhkd-statusd -l verbose /run/user/1000/sxhkd.fifo
The sxhkd pipe "/run/user/1000/sxhkd.fifo" has open as fd[3]
The server socket has initialized at "/run/user/1000/sxhkd.fifo.sxhkd-statusd", as fd[7]
sxhkd event from fd[3]: Hsuper + h
```

I found that the error occurs in `src/event.c` in function `sxhkd_event`. `send` fails. I think with signal `SIGPIPE` (which explains the exit code 141 = 128 + 13).

One way I found to fix this is to use the `MSG_NOSIGNAL` flag for `send`. Or you could check if the fd is writable.

**Comment by piutranq** [comment]
I couldn't reproduce the error, but I used the `MSG_NOSIGNAL` flag for `send()` as you told me.

https://github.com/piutranq/sxhkd-statusd/commit/2604722b1e76352b934fcc1a00f8345e1121482e

**Comment by Lythenas** [comment]
Thanks that works for me.

Maybe the behavior is different when using different distros, shells or terminal emulators. I'm Arch using Fish (shell) and Alacritty (term).
