### ISSUE TITLE
(doc only) error in README

### ISSUE THREAD

**Issue by davison** [piutranq/sxhkd-statusd#2]
I think `socat UNIX_CONNECT:/run/user/$UID/sxhkd.fifo.sxhkd-statusd -` at the end of the README should be `UNIX-CONNECT`

**Comment by piutranq** [comment]
Thanks for reporting the typo. It has been fixed.

https://github.com/piutranq/sxhkd-statusd/commit/6d26c691546166d687d19c2405748e02a72c0339
