### ISSUE TITLE
Can't make socat connect to the fifo

### ISSUE THREAD

**Issue by davison** [piutranq/sxhkd-statusd#3]
in one terminal;

```
~ $ rm -f /run/user/1000/sxhkd.fifo 
~ $ mkfifo /run/user/1000/sxhkd.fifo
~ $ ls -al /run/user/1000/sxhkd.fifo 
prw-rw-r-- 1 darren darren 0 Feb  1 00:33 /run/user/1000/sxhkd.fifo|
~ $ sxhkd-statusd -l verbose /run/user/1000/sxhkd.fifo

```

then in second terminal;

```
~ $ socat UNIX-CONNECT:/run/user/1000/sxhkd.fifo.sxhkd-statusd -
2021/02/01 00:37:33 socat[2948191] E connect(5, AF=1 "/run/user/1000/sxhkd.fifo.sxhkd-statusd", 41): No such file or directory
```

did I miss a step? 

(This assumes #2 is valid since if I use the documented version I get instead `socat[2948388] E unknown device/address "UNIX_CONNECT"`)

**Comment by piutranq** [comment]
1. Have you launched the sxhkd with the pipe `/run/user/1000/sxhkd.fifo` ?  If not, use the `-s` option to launch sxhkd with the pipe (see `man sxhkd`) after making the pipe, before launching sxhkd-statusd.

2. Is the socket file `/run/user/1000/sxhkd.fifo.sxhkd-statusd` created after launching sxhkd-statusd? When sxhkd-statusd is launched it should create the socket file automatically.

**Comment by davison** [comment]
ah.. another late night fail :( Yeah, had done that but then killed and restarted sxhkd without it. Thanks, looks good.
